# Generated by Django 6.0.3 on 2026-04-18 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.phonemodel')),
            ],
        ),
    ]
